import type { FullMatchAnalysis, AlgorithmResult, OddsMovement } from '@/lib/types'

function makeOddsHistory(openHome: number, openAway: number, openHdp: number) {
  return Array.from({ length: 12 }, (_, i) => ({
    timestamp: new Date(Date.now() - (11 - i) * 3600_000).toISOString(),
    home: parseFloat((openHome + (Math.random() - 0.5) * 0.08 * i * 0.3).toFixed(2)),
    draw: parseFloat((3.3 + (Math.random() - 0.5) * 0.1).toFixed(2)),
    away: parseFloat((openAway + (Math.random() - 0.5) * 0.08 * i * 0.3).toFixed(2)),
    hdp: parseFloat((openHdp + (Math.random() - 0.5) * 0.1 * i * 0.2).toFixed(2)),
    volume: Math.floor(80 + Math.random() * 220),
  }))
}

const ALGO_NAMES: { name: string; engine: 'Python' | 'Node.js'; weight: number }[] = [
  { name: 'Weighted Poisson Distribution',        engine: 'Python',   weight: 0.20 },
  { name: 'Reverse Line Movement',                 engine: 'Node.js',  weight: 0.20 },
  { name: 'Monte Carlo Simulation',                engine: 'Python',   weight: 0.15 },
  { name: 'HDP vs 1x2 Deviation',                  engine: 'Node.js',  weight: 0.15 },
  { name: 'Public Sentiment Bias',                 engine: 'Python',   weight: 0.10 },
  { name: 'Early vs Late Odds Deviation',          engine: 'Node.js',  weight: 0.10 },
  { name: 'Asian Handicap Insurance Detection',    engine: 'Node.js',  weight: 0.05 },
  { name: 'League Cluster Pattern',                engine: 'Python',   weight: 0.05 },
]

const ALGO_DETAILS: string[][] = [
  ['Attack strength delta high', 'Balanced expected goals', 'Strong home attack advantage'],
  ['RLM confirmed — sharp vs public', 'Partial RLM signal', 'No line movement detected'],
  ['10k sims: away cover 58%', '10k sims: balanced output', 'Home win 62% simulations'],
  ['Implied gap 7.2 pts', 'Minor deviation 3.1 pts', 'Gap within normal range'],
  ['Hype index 83/100', 'Moderate hype 54/100', 'Low sentiment bias'],
  ['Late steam detected -0.12', 'Stable lines', 'Early money confirmed direction'],
  ['+0.25 movement detected', 'No insurance signals', 'DNB appeared briefly'],
  ['EPL cluster 73% match', 'La Liga cluster 61%', 'Bundesliga pattern 71%'],
]

export function generateAlgorithms(trapScore: number): AlgorithmResult[] {
  return ALGO_NAMES.map((algo, i) => {
    const base = Math.max(5, Math.min(95, trapScore + (Math.random() - 0.5) * 30))
    const score = Math.round(base)
    const signal: AlgorithmResult['signal'] =
      score >= 70 ? 'TRAP' : score >= 50 ? 'WARN' : score >= 30 ? 'NEUTRAL' : 'SAFE'
    const details = ALGO_DETAILS[i]
    const detail = details[Math.floor(Math.random() * details.length)]
    return { id: i + 1, name: algo.name, engine: algo.engine, score, signal, detail, weight: algo.weight }
  })
}

export function generateOddsHistory(openHome: number, openAway: number, points = 12): OddsMovement[] {
  const openHdp = -0.5
  return Array.from({ length: points }, (_, i) => ({
    timestamp: new Date(Date.now() - (points - 1 - i) * 3600_000).toISOString(),
    home: parseFloat((openHome + (Math.random() - 0.5) * 0.08 * i * 0.3).toFixed(2)),
    draw: parseFloat((3.3 + (Math.random() - 0.5) * 0.1).toFixed(2)),
    away: parseFloat((openAway + (Math.random() - 0.5) * 0.08 * i * 0.3).toFixed(2)),
    hdp: parseFloat((openHdp + (Math.random() - 0.5) * 0.1 * i * 0.2).toFixed(2)),
    volume: Math.floor(80 + Math.random() * 220),
  }))
}

export const MOCK_MATCHES: FullMatchAnalysis[] = [
  {
    id: '1',
    home_team: 'Manchester City',
    away_team: 'Arsenal',
    kick_off: new Date(Date.now() + 2 * 3600_000).toISOString(),
    league: 'English Premier League',
    league_key: 'epl',
    league_country: 'England',
    status: 'scheduled',
    analysis: {
      match_id: '1',
      opening_hdp: -0.75,
      current_hdp: -0.5,
      opening_odds_home: 1.88,
      opening_odds_draw: 3.5,
      opening_odds_away: 4.2,
      current_odds_home: 1.95,
      current_odds_draw: 3.4,
      current_odds_away: 3.95,
      public_volume_home: 72,
      public_volume_away: 18,
      public_volume_draw: 10,
      trap_score: 82,
      recommendation: 'ANTITESIS',
      confidence: 87,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 78, signal: 'TRAP', detail: 'Attack strength delta 0.38', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 91, signal: 'TRAP', detail: 'RLM confirmed — sharp vs public', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 74, signal: 'TRAP', detail: '10k sims: away cover 58%', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 88, signal: 'TRAP', detail: 'Implied gap 7.2 pts', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 85, signal: 'TRAP', detail: 'Hype index 83/100', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 77, signal: 'TRAP', detail: 'Late steam -0.12 away', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 62, signal: 'WARN', detail: '+0.25 movement detected', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 80, signal: 'TRAP', detail: 'EPL cluster: 73% match', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(1.88, 4.2, -0.75),
    home_stats: { team_id: 'mci', team_name: 'Manchester City', attack_strength: 1.62, defence_strength: 0.71, avg_goals_scored: 2.4, avg_goals_conceded: 0.9, last_5_form: ['W','W','D','W','W'], poisson_home: 2.1, poisson_away: 1.0 },
    away_stats: { team_id: 'ars', team_name: 'Arsenal', attack_strength: 1.48, defence_strength: 0.82, avg_goals_scored: 2.1, avg_goals_conceded: 1.1, last_5_form: ['W','D','W','W','L'], poisson_home: 1.8, poisson_away: 1.2 },
    sentiment_score: 83,
    sentiment_summary: 'Overwhelming public backing for Manchester City despite sharp indicators pointing to Arsenal covering. Classic trap pattern with 72% public volume on City.',
    smart_money_detected: true,
    rlm_active: true,
  },
  {
    id: '2',
    home_team: 'Real Madrid',
    away_team: 'Barcelona',
    kick_off: new Date(Date.now() + 5 * 3600_000).toISOString(),
    league: 'La Liga',
    league_key: 'laliga',
    league_country: 'Spain',
    status: 'scheduled',
    analysis: {
      match_id: '2',
      opening_hdp: -0.5,
      current_hdp: -0.5,
      opening_odds_home: 2.05,
      opening_odds_draw: 3.3,
      opening_odds_away: 3.6,
      current_odds_home: 2.10,
      current_odds_draw: 3.25,
      current_odds_away: 3.55,
      public_volume_home: 64,
      public_volume_away: 24,
      public_volume_draw: 12,
      trap_score: 61,
      recommendation: 'MONITOR',
      confidence: 72,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 58, signal: 'WARN', detail: 'Balanced expected goals', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 68, signal: 'WARN', detail: 'Partial RLM signal', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 55, signal: 'NEUTRAL', detail: '10k sims: balanced', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 62, signal: 'WARN', detail: 'Minor gap 3.1 pts', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 71, signal: 'WARN', detail: 'High Clasico interest', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 48, signal: 'NEUTRAL', detail: 'Stable lines', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 44, signal: 'NEUTRAL', detail: 'No insurance signals', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 60, signal: 'WARN', detail: 'La Liga cluster 61%', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(2.05, 3.6, -0.5),
    home_stats: { team_id: 'rma', team_name: 'Real Madrid', attack_strength: 1.55, defence_strength: 0.78, avg_goals_scored: 2.2, avg_goals_conceded: 1.0, last_5_form: ['W','W','W','D','W'], poisson_home: 1.9, poisson_away: 1.1 },
    away_stats: { team_id: 'fcb', team_name: 'Barcelona', attack_strength: 1.52, defence_strength: 0.80, avg_goals_scored: 2.1, avg_goals_conceded: 1.0, last_5_form: ['W','W','D','W','L'], poisson_home: 1.8, poisson_away: 1.2 },
    sentiment_score: 71,
    sentiment_summary: 'El Clasico generates enormous social buzz with moderate trap indicators. Watch for late line movement as sharp money typically enters closer to kick-off.',
    smart_money_detected: false,
    rlm_active: false,
  },
  {
    id: '3',
    home_team: 'Bayern Munich',
    away_team: 'Borussia Dortmund',
    kick_off: new Date(Date.now() + 8 * 3600_000).toISOString(),
    league: 'Bundesliga',
    league_key: 'bundesliga',
    league_country: 'Germany',
    status: 'scheduled',
    analysis: {
      match_id: '3',
      opening_hdp: -1.0,
      current_hdp: -0.75,
      opening_odds_home: 1.72,
      opening_odds_draw: 3.9,
      opening_odds_away: 4.8,
      current_odds_home: 1.78,
      current_odds_draw: 3.85,
      current_odds_away: 4.6,
      public_volume_home: 78,
      public_volume_away: 14,
      public_volume_draw: 8,
      trap_score: 77,
      recommendation: 'ANTITESIS',
      confidence: 83,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 72, signal: 'TRAP', detail: 'Attack differential reduced', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 86, signal: 'TRAP', detail: 'HDP steamed up 0.25', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 69, signal: 'WARN', detail: 'BVB cover 42%', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 80, signal: 'TRAP', detail: 'Implied gap 5.8 pts', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 82, signal: 'TRAP', detail: 'Der Klassiker hype 79/100', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 71, signal: 'TRAP', detail: 'Late movement -0.08', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 58, signal: 'WARN', detail: 'Quarter ball shift noted', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 75, signal: 'TRAP', detail: 'Bundesliga match 71%', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(1.72, 4.8, -1.0),
    home_stats: { team_id: 'fcb', team_name: 'Bayern Munich', attack_strength: 1.71, defence_strength: 0.68, avg_goals_scored: 2.7, avg_goals_conceded: 0.8, last_5_form: ['W','W','W','W','D'], poisson_home: 2.3, poisson_away: 0.9 },
    away_stats: { team_id: 'bvb', team_name: 'Borussia Dortmund', attack_strength: 1.39, defence_strength: 0.91, avg_goals_scored: 1.9, avg_goals_conceded: 1.3, last_5_form: ['L','W','D','W','W'], poisson_home: 1.6, poisson_away: 1.4 },
    sentiment_score: 79,
    sentiment_summary: 'Der Klassiker public money heavily on Bayern but line movement tells a different story. Sharp bettors backing BVB to cover the inflated handicap.',
    smart_money_detected: true,
    rlm_active: true,
  },
  {
    id: '4',
    home_team: 'PSG',
    away_team: 'Marseille',
    kick_off: new Date(Date.now() + 12 * 3600_000).toISOString(),
    league: 'Ligue 1',
    league_key: 'ligue1',
    league_country: 'France',
    status: 'scheduled',
    analysis: {
      match_id: '4',
      opening_hdp: -0.75,
      current_hdp: -0.75,
      opening_odds_home: 1.65,
      opening_odds_draw: 3.8,
      opening_odds_away: 5.2,
      current_odds_home: 1.68,
      current_odds_draw: 3.75,
      current_odds_away: 5.0,
      public_volume_home: 69,
      public_volume_away: 20,
      public_volume_draw: 11,
      trap_score: 44,
      recommendation: 'NEUTRAL',
      confidence: 61,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 42, signal: 'NEUTRAL', detail: 'Expected: PSG 1.8 vs 0.9', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 38, signal: 'SAFE', detail: 'Line stable, no RLM', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 45, signal: 'NEUTRAL', detail: 'PSG win 58% sims', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 40, signal: 'NEUTRAL', detail: 'Small gap 2.1 pts', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 55, signal: 'WARN', detail: 'Moderate hype 54/100', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 36, signal: 'SAFE', detail: 'Stable through session', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 41, signal: 'NEUTRAL', detail: 'No anomalies', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 50, signal: 'NEUTRAL', detail: 'Ligue 1 base rate', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(1.65, 5.2, -0.75),
    home_stats: { team_id: 'psg', team_name: 'PSG', attack_strength: 1.68, defence_strength: 0.72, avg_goals_scored: 2.5, avg_goals_conceded: 0.9, last_5_form: ['W','W','W','W','W'], poisson_home: 2.2, poisson_away: 0.8 },
    away_stats: { team_id: 'om', team_name: 'Marseille', attack_strength: 1.22, defence_strength: 0.98, avg_goals_scored: 1.6, avg_goals_conceded: 1.4, last_5_form: ['W','D','L','W','D'], poisson_home: 1.3, poisson_away: 1.5 },
    sentiment_score: 52,
    sentiment_summary: 'Le Classique generates solid buzz but market indicators are relatively clean. PSG priced efficiently with no significant sharp action detected.',
    smart_money_detected: false,
    rlm_active: false,
  },
  {
    id: '5',
    home_team: 'Juventus',
    away_team: 'AC Milan',
    kick_off: new Date(Date.now() + 18 * 3600_000).toISOString(),
    league: 'Serie A',
    league_key: 'seriea',
    league_country: 'Italy',
    status: 'scheduled',
    analysis: {
      match_id: '5',
      opening_hdp: -0.25,
      current_hdp: 0.0,
      opening_odds_home: 2.15,
      opening_odds_draw: 3.2,
      opening_odds_away: 3.4,
      current_odds_home: 2.25,
      current_odds_draw: 3.15,
      current_odds_away: 3.2,
      public_volume_home: 58,
      public_volume_away: 28,
      public_volume_draw: 14,
      trap_score: 68,
      recommendation: 'MONITOR',
      confidence: 76,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 63, signal: 'WARN', detail: 'Juve attack dipped', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 74, signal: 'TRAP', detail: 'Milan steam overnight', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 60, signal: 'WARN', detail: 'Milan cover 46% sims', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 72, signal: 'WARN', detail: 'Line moved full handicap', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 65, signal: 'WARN', detail: 'Juve bias 58/100', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 70, signal: 'WARN', detail: 'Late money on Milan', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 55, signal: 'WARN', detail: 'DNB appeared briefly', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 66, signal: 'WARN', detail: 'Serie A match 64%', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(2.15, 3.4, -0.25),
    home_stats: { team_id: 'juv', team_name: 'Juventus', attack_strength: 1.35, defence_strength: 0.85, avg_goals_scored: 1.8, avg_goals_conceded: 1.1, last_5_form: ['D','W','L','W','D'], poisson_home: 1.6, poisson_away: 1.3 },
    away_stats: { team_id: 'acm', team_name: 'AC Milan', attack_strength: 1.44, defence_strength: 0.88, avg_goals_scored: 1.9, avg_goals_conceded: 1.2, last_5_form: ['W','W','D','W','L'], poisson_home: 1.7, poisson_away: 1.4 },
    sentiment_score: 61,
    sentiment_summary: 'Derby d\'Italia showing interesting line movement toward Milan. Handicap steamed from -0.25 to level ball suggesting sharp interest in the away side.',
    smart_money_detected: true,
    rlm_active: false,
  },
  {
    id: '6',
    home_team: 'Liverpool',
    away_team: 'Chelsea',
    kick_off: new Date(Date.now() + 26 * 3600_000).toISOString(),
    league: 'English Premier League',
    league_key: 'epl',
    league_country: 'England',
    status: 'scheduled',
    analysis: {
      match_id: '6',
      opening_hdp: -0.5,
      current_hdp: -0.5,
      opening_odds_home: 1.95,
      opening_odds_draw: 3.4,
      opening_odds_away: 3.9,
      current_odds_home: 1.92,
      current_odds_draw: 3.45,
      current_odds_away: 4.0,
      public_volume_home: 61,
      public_volume_away: 26,
      public_volume_draw: 13,
      trap_score: 35,
      recommendation: 'PRO_STATS',
      confidence: 69,
      last_updated: new Date().toISOString(),
    },
    algorithms: [
      { id: 1, name: 'Weighted Poisson Distribution', engine: 'Python', score: 30, signal: 'SAFE', detail: 'Liverpool expected 1.9 goals', weight: 0.20 },
      { id: 2, name: 'Reverse Line Movement', engine: 'Node.js', score: 28, signal: 'SAFE', detail: 'Public + sharp aligned', weight: 0.20 },
      { id: 3, name: 'Monte Carlo Simulation', engine: 'Python', score: 35, signal: 'SAFE', detail: 'Liverpool win 54%', weight: 0.15 },
      { id: 4, name: 'HDP vs 1x2 Deviation', engine: 'Node.js', score: 32, signal: 'SAFE', detail: 'Gap within normal 1.8 pts', weight: 0.15 },
      { id: 5, name: 'Public Sentiment Bias', engine: 'Python', score: 48, signal: 'NEUTRAL', detail: 'Moderate hype 44/100', weight: 0.10 },
      { id: 6, name: 'Early vs Late Odds Deviation', engine: 'Node.js', score: 30, signal: 'SAFE', detail: 'Consistent pricing', weight: 0.10 },
      { id: 7, name: 'Asian Handicap Insurance Detection', engine: 'Node.js', score: 38, signal: 'NEUTRAL', detail: 'No insurance', weight: 0.05 },
      { id: 8, name: 'League Cluster Pattern', engine: 'Python', score: 42, signal: 'NEUTRAL', detail: 'EPL clean signal 38%', weight: 0.05 },
    ],
    odds_history: makeOddsHistory(1.95, 3.9, -0.5),
    home_stats: { team_id: 'liv', team_name: 'Liverpool', attack_strength: 1.58, defence_strength: 0.75, avg_goals_scored: 2.3, avg_goals_conceded: 1.0, last_5_form: ['W','W','W','D','W'], poisson_home: 2.0, poisson_away: 1.0 },
    away_stats: { team_id: 'che', team_name: 'Chelsea', attack_strength: 1.31, defence_strength: 0.92, avg_goals_scored: 1.7, avg_goals_conceded: 1.2, last_5_form: ['D','W','D','L','W'], poisson_home: 1.5, poisson_away: 1.5 },
    sentiment_score: 44,
    sentiment_summary: 'Liverpool vs Chelsea shows clean market pricing with public and sharp money aligned. Statistics favour Liverpool with no significant trap indicators.',
    smart_money_detected: false,
    rlm_active: false,
  },
]
